### ISSUE TITLE
leds doesn't blink

### ISSUE THREAD

**Issue by ghost** [mitwo-dev/android_device_xiaomi_aries#13]
i test these leds(red,green,blue) on the new kernel.however,they doesn't blink.i think this is kernel bug.In MIUI,if echo 1 >/sys/class/led/red/brightness ,the red led will blink.
however,it doesn't blink on the new kernel.
by the way,the new kernel will support custom blinking freq(/sys/class/leds/red/device/grpfreq),as like mako?

**Comment by M1cha** [comment]
Do you mean it doesn't light up at all or that it just does not blink?
Blinking is non-standard and was a mod by xiaomi.

**Comment by ghost** [comment]
It lights up but not breath blinking like miui.And I can't some file that control blinking freq.

**Comment by ivan19871002** [comment]
does not support blink in miui.

**Comment by grondinm** [comment]
so i'm confused. if the led is able to blink in MIUI it should be able to blink in other roms. For example AOKP has option for setting blink pattern/frequency but these settings do not change anything the led still stays solid. This sounds like something that can be fixed in the led driver...

**Comment by M1cha** [comment]
yep but making the led blink by default is very hardcoded. Doing this means we would have to disable PWM feature and set a blinking pattern.

**Comment by grondinm** [comment]
This issue is solved with the latest 4.3 kernel..i hope they can bring this to the cm-10.1 kernel as well....

**Comment by ivan19871002** [comment]
wait , i will bring this to cm-10.1 kernel.

**Comment by ivan19871002** [comment]
fix on cm10.1

**Comment by grondinm** [comment]
thank you.
