### ISSUE TITLE
CPU Frequency changes only affect Core 0

### ISSUE THREAD

**Issue by grondinm** [mitwo-dev/android_device_xiaomi_aries#14]
This has been reported on multiple roms using the latest kernel. I have confirmed it on AOKP. if i use any app(No frills cpu control or cpu tweeker) to set the max frequency of the CPU  to 384(as an example) it only affects the first core (Core 0). I watched the core frequencies using z-cpu and the other cores still spike to 1512 and hit pretty much all other steps as well.

**Comment by Ryotsuke** [comment]
I confirm same bug exists on recent Magic Fun Rom(http://www.weibo.com/sheepkx) and cofface's CM10.1 ROM(http://www.weibo.com/cofface)

**Comment by grondinm** [comment]
seems the folder cpufreq is missing for cpu1,cpu2 and cpu3 this is probably the cause. I can't come up with any reason why that folder is not created on all 4 cores....

**Comment by ivan19871002** [comment]
不是内核的bug。你们自己好好看配置文件或者是cm的代码

**Comment by Ryotsuke** [comment]
No, this should be in kernel driver. 

Currently writing values in /sys/devices/system/cpu/cpu0/cpufreq/\* does nothing, as is being overridden by some kernel driver later dynamically. Only core 1(#0) is affected as it is permanently on.
Mi2 is multi-core. Cores 2-4 are turned on dynamically. 

Even if some values are set in cpufreq/2-4 manually (like max 1242) they are not enabled before core is on, and when core is on they are rewritten with default values. And cores 2-4 still jump to high values, ignoring cpufreq. Basically no external control for core 2-4 is available, so CM config has nothing to do with it, this should be kernel driver bug.

**Comment by ivan19871002** [comment]
于 13-8-15 下午2:21, Ryotsuke 写道:

> Currently writing values in /sys/devices/system/cpu/cpu0/cpufreq/\* 
> does nothing, as is being overridden by some kernel driver later 
> dynamically. Only core 1(#0) is affected as it is permanently on.
> Mi2 is multi-core. Cores 2-4 are turned on dynamically.
> 
> Even if some values are set in cpufreq/2-4 manually (like max 1242) 
> they are not enabled before core is on, and when core is on they are 
> rewritten with default values. And cores 2-4 still jump to high 
> values, ignoring cpufreq. Basically no external control for core 2-4 
> is available, so CM config has nothing to do with it, this should be 
> kernel driver bug.

The cpu driver like  sony 8064 , i cherry-pick  follow it .
