### ISSUE TITLE
LED show wrong light

### ISSUE THREAD

**Issue by Ryotsuke** [mitwo-dev/android_device_xiaomi_aries#15]
MIUI rom:
Notification: blue led active
Charging: red led active (or yellow blonkin, i don't quite remember)
Charged: green led

Current ROMS built with recent CM10.1 kernel:
This applies for Magic Fun Rom 20130814
Notification: all colors active at same time
Charged: no LED is active at all

This is related to https://github.com/mitwo-dev/android_device_xiaomi_aries/issues/13 but not the same

**Comment by grondinm** [comment]
This is not a bug...since like you pointed out in MIUI the colors are set to those by default. in CM10 the defualts are different. The charge led is something to be worked on and also the color support but this is not a bug....

**Comment by Ryotsuke** [comment]
So this is likely CM10.1 bug, rather than kernel one?

**Comment by grondinm** [comment]
well it's related to CM10.1 but not really a bug when it comes to the default color of the led...it's just set different in cm10.1...the charging led may be more kernel/led driver related.
