### ISSUE TITLE
Problem with screenshot 

### ISSUE THREAD

**Issue by kekkojoker90** [mitwo-dev/android_device_xiaomi_aries#16]
In the build of cm combination for the made a screenshot don't work. I don't know if is a bug or a missing in the cyanogen repo. Thanks PS if you can add a way to swith to first and second system and to reboot in recovery help a lot :P

**Comment by ivan19871002** [comment]
use m1cha's recovery

**Comment by kekkojoker90** [comment]
I already have clocworkmod of m1cha but i think i have made a mistake when i explain the problem. If i want take a screenshot with this version of cyanogenmod because menu+volume down don't work. And my second request (but i think is a compiler fault) is a way to switch from system 1 e 2 without going in the recovery.
