### ISSUE TITLE
Camera issuses with staging/android-5.1.1 tag

### ISSUE THREAD

**Issue by 1304073402** [mitwo-dev/android_device_xiaomi_aries#27]
@M1cha 
Camera can not work with staging/android-5.1.1 source,and have ramdom reboot.

09:43:03.139 Error AudioTrack 5153  AudioTrack::set : Exit
09:43:03.247 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.248 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.250 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.250 Error mm-camera 289  AWB CALI rg:0x0000, bg:0000 rb:0000
09:43:03.576 Error mm-camera 289  sensor_load_chromatix: libchromatix_s5k3h7a_preview.so: 31
09:43:03.576 Error mm-camera 289  Failed to dlopen libchromatix_s5k3h7a_preview.so: dlopen failed: library "libchromatix_s5k3h7a_preview.so" not found
09:43:03.576 Error mm-camera 289  sensor_init:198:Error:Failed to load chromatix file
09:43:03.576 Error mm-camera 289  mctl_init: sensor_interface_init failed: handle = 0x2900, rc = -22
09:43:03.577 Error mm-camera 289  cam_mctl_thread: mctl_init() error
09:43:03.577 Error mm-camera 289  wait_cam_mctl_thread_ready: mctl thread opened but failed during init
09:43:03.577 Error mm-libcamera2 4867  mm_camera_open:  ctrl_fd = 42
09:43:03.577 Error mm-libcamera2 4867  Errno:0
09:43:03.577 Error mm-libcamera2 4867  mm_camera_open:  opened, break out while loop
09:43:03.577 Error mm-libcamera2 4867  mm_camera_open:  after while loop
09:43:03.577 Error mm-libcamera2 4867  mm_camera_open:  2
09:43:03.578 Error mm-libcamera2 4867  mm_camera_socket_create: socket_fd=-1 No such file or directory
09:43:03.578 Error mm-libcamera2 4867  mm_camera_open:  ds_fd = -1
09:43:03.578 Error mm-libcamera2 4867  Errno:2
09:43:03.578 Error mm-libcamera2 4867  mm_camera_socket_create: socket_fd=-1 No such file or directory
09:43:03.578 Error mm-libcamera2 4867  mm_camera_open:  ds_fd = -1
09:43:03.578 Error mm-libcamera2 4867  Errno:2
09:43:03.578 Error mm-libcamera2 4867  mm_camera_open:  opened, break out while loop
09:43:03.579 Error mm-libcamera2 4867  mm_camera_open:  after while loop for domain socket open
09:43:03.579 Error mm-libcamera2 4867  mm_camera_open: cannot open domain socket fd of 'video0' Errno = 2
09:43:03.579 Error QCameraHWI 4867  startCamera: cam_ops_open failed: id = 0
09:43:03.579 Error QCameraHWI 4867  isCameraReady mCameraState 0
09:43:03.579 Error QualcommCamera 4867  int android::camera_device_open(const hw_module_t_, char const_, hw_device_t__):  end rc -1
09:43:03.580 Error CameraClient 4867  Could not open camera 0: -19
09:43:03.580 Error CameraClient 4867  initialize: Camera 0: unable to initialize device: No such device (-19)
09:43:03.580 Error CameraService 4867  connectFinishUnsafe: Could not initialize client from HAL module.
09:43:03.581 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.581 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.581 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.683 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.683 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.685 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.686 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.686 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.902 Error QualcommCamera 4867  Qint android::get_camera_info(int, camera_info_): E
09:43:03.905 Error mm-camera 289  AWB CALI rg:0x0000, bg:0000 rb:0000
09:43:04.119 Error mm-camera 289  sensor_load_chromatix: libchromatix_s5k3h7a_preview.so: 31
09:43:04.119 Error mm-camera 289  Failed to dlopen libchromatix_s5k3h7a_preview.so: dlopen failed: library "libchromatix_s5k3h7a_preview.so" not found
09:43:04.119 Error mm-camera 289  sensor_init:198:Error:Failed to load chromatix file
09:43:04.120 Error mm-camera 289  mctl_init: sensor_interface_init failed: handle = 0x2a00, rc = -22
09:43:04.120 Error mm-camera 289  cam_mctl_thread: mctl_init() error
09:43:04.120 Error mm-camera 289  wait_cam_mctl_thread_ready: mctl thread opened but failed during init
09:43:04.120 Error mm-libcamera2 4867  mm_camera_open:  ctrl_fd = 49
09:43:04.120 Error mm-libcamera2 4867  Errno:0
09:43:04.120 Error mm-libcamera2 4867  mm_camera_open:  opened, break out while loop
09:43:04.120 Error mm-libcamera2 4867  mm_camera_open:  after while loop
09:43:04.121 Error mm-libcamera2 4867  mm_camera_open:  2
09:43:04.121 Error mm-libcamera2 4867  mm_camera_socket_create: socket_fd=-1 No such file or directory
09:43:04.121 Error mm-libcamera2 4867  mm_camera_open:  ds_fd = -1
09:43:04.121 Error mm-libcamera2 4867  Errno:2
09:43:04.121 Error mm-libcamera2 4867  mm_camera_socket_create: socket_fd=-1 No such file or directory
09:43:04.122 Error mm-libcamera2 4867  mm_camera_open:  ds_fd = -1
09:43:04.122 Error mm-libcamera2 4867  Errno:2
09:43:04.122 Error mm-libcamera2 4867  mm_camera_open:  opened, break out while loop
09:43:04.122 Error mm-libcamera2 4867  mm_camera_open:  after while loop for domain socket open
09:43:04.122 Error mm-libcamera2 4867  mm_camera_open: cannot open domain socket fd of 'video0' Errno = 2
09:43:04.122 Error QCameraHWI 4867  startCamera: cam_ops_open failed: id = 0
09:43:04.123 Error QCameraHWI 4867  isCameraReady mCameraState 0
09:43:04.123 Error QualcommCamera 4867  int android::camera_device_open(const hw_module_t_, char const_, hw_device_t**):  end rc -1
09:43:04.123 Error CameraClient 4867  Could not open camera 0: -19
09:43:04.123 Error CameraClient 4867  initialize: Camera 0: unable to initialize device: No such device (-19)
09:43:04.123 Error CameraService 4867  connectFinishUnsafe: Could not initialize client from HAL module.
09:43:04.229 Error CAM2PORT_AndCamAgntImp 8446  RuntimeException during CameraAction[OPEN_CAMERA] at CameraState[1]
09:43:04.229 Error CAM2PORT_AndCamAgntImp 8446  java.lang.RuntimeException: Fail to connect to camera service
09:43:04.229 Error CAM2PORT_AndCamAgntImp 8446      at android.hardware.Camera.<init>(Camera.java:529)
09:43:04.230 Error CAM2PORT_AndCamAgntImp 8446      at android.hardware.Camera.open(Camera.java:364)
09:43:04.230 Error CAM2PORT_AndCamAgntImp 8446      at com.android.ex.camera2.portability.AndroidCameraAgentImpl$CameraHandler.handleMessage(AndroidCameraAgentImpl.java:370)
09:43:04.230 Error CAM2PORT_AndCamAgntImp 8446      at android.os.Handler.dispatchMessage(Handler.java:102)
09:43:04.230 Error CAM2PORT_AndCamAgntImp 8446      at android.os.Looper.loop(Looper.java:135)
09:43:04.230 Error CAM2PORT_AndCamAgntImp 8446      at android.os.HandlerThread.run(HandlerThread.java:61)
09:43:04.230 Error CAM_Util 8446  Show fatal error dialog
09:43:07.176 Error AudioTrack 5153  AudioTrack::set : Exit

**Comment by M1cha** [comment]
this branch is deprecated. new sources will be uploaded soon

**Comment by 1304073402** [comment]
ok, ths

**Comment by Mirsaid02** [comment]
M1cha, May You suggest any solution for this issue?

**Comment by Mirsaid02** [comment]
Because I have the same
