### ISSUE TITLE
freq_max,freq_min,freq_gov in CM's performance not available

### ISSUE THREAD

**Issue by ghost** [mitwo-dev/android_device_xiaomi_aries#5]
logcat:
E/Utils   ( 1042): Error writing to /sys/devices/system/cpu/cpu0/cpufreq/scaling
_max_freq. Exception:
E/Utils   ( 1042): java.io.FileNotFoundException: /sys/devices/system/cpu/cpu0/c
pufreq/scaling_max_freq: open failed: EACCES (Permission denied)

E/Utils   ( 1042): Error writing to /sys/devices/system/cpu/cpu0/cpufreq/scaling
_min_freq. Exception:
E/Utils   ( 1042): java.io.FileNotFoundException: /sys/devices/system/cpu/cpu0/c
pufreq/scaling_max_freq: open failed: EACCES (Permission denied)

E/Utils   ( 1042): Error writing to /sys/devices/system/cpu/cpu0/cpufreq/scaling
_governor. Exception:
E/Utils   ( 1042): java.io.FileNotFoundException: /sys/devices/system/cpu/cpu0/c
pufreq/scaling_governor: open failed: EACCES (Permission denied)

**Comment by ivan19871002** [comment]
-rw-rw-r-- system   system       4096 1970-01-08 01:45 scaling_governor
-rw-rw-r-- system   system       4096 1970-01-08 01:51 scaling_max_freq
-rw-rw---- system   system       4096 1970-01-08 01:51 scaling_min_freq

this is permission. that is right

**Comment by ghost** [comment]
but,I checked these in Root Explorer,scaling_governor,scaling_max_freq and scaling_min_freq 's filemode are -r--r--r--.I am using cofface's rom.I don't know which scripts changes it.I have searched every init scripts,it seems that nothing is wrong. By the way,the power HAL(power.aries.so) reports error because scaling_min_freq is not writable.

**Comment by ivan19871002** [comment]
you can change it in init.aries.rc

**Comment by ghost** [comment]
Solved.The problem causes by CM.
