### ISSUE TITLE
front camera not available

### ISSUE THREAD

**Issue by ghost** [mitwo-dev/android_device_xiaomi_aries#6]
logcat:

D/CameraWrapper(  236): camera_disable_msg_type->41528FC0->41529018
D/CameraWrapper(  236): camera_disable_msg_type
D/CameraWrapper(  236): camera_disable_msg_type->41528FC0->41529018
D/CameraWrapper(  236): camera_disable_msg_type
D/CameraWrapper(  236): camera_stop_preview
D/CameraWrapper(  236): camera_stop_preview->41528FC0->41529018
E/QualcommCamera(  236): Qvoid android::stop_preview(camera_device_): E
E/QCameraHWI_Preview(  236): virtual void android::QCameraStream_preview::stop()
: E
E/mm-camera(  251): ispif_client_process: event type =6
E/mm-camera(  251): ispif_parse_handle: handle = 0x100, client_idx = 0
E/mm-camera(  251): ispif_process_stop_immediately called
E/mm-camera(  251): mctl_pp_poll_fn: Woke up Socket fd
E/mm-camera(  251): mctl_pp_recvmsg: Receieved msg_type=1
E/mm-camera(  251): mctl_pp_poll_fn: Woke up Socket fd
E/mm-camera(  251): mctl_pp_recvmsg: Receieved msg_type=1
E/mm-camera(  251): mctl_pp_poll_fn: Woke up Socket fd
E/mm-camera(  251): mctl_pp_recvmsg: Receieved msg_type=1
E/mm-camera(  251): mctl_pp_poll_fn: Woke up Socket fd
E/mm-camera(  251): mctl_pp_recvmsg: Receieved msg_type=1
E/mm-camera(  251): mctl_pp_poll_fn: Woke up Socket fd
E/mm-camera(  251): mctl_pp_recvmsg: Receieved msg_type=1
E/mm-camera(  251): mctl_pp_poll_fn: Woke up Socket fd
E/mm-camera(  251): mctl_pp_recvmsg: Receieved msg_type=1
E/mm-camera(  251): mctl_pp_poll_fn: Woke up Socket fd
E/mm-camera(  251): mctl_pp_recvmsg: Receieved msg_type=1
E/QCameraHWI_Preview(  236): virtual void android::QCameraStream_preview::stop()
: X
D/CameraWrapper(  236): camera_cancel_picture
D/CameraWrapper(  236): camera_cancel_picture->41528FC0->41529018
E/QualcommCamera(  236): Qint android::cancel_picture(camera_device_): E
D/CameraWrapper(  236): camera_release
D/CameraWrapper(  236): camera_release->41528FC0->41529018
E/QualcommCamera(  236): Qvoid android::release(camera_device_): E
D/CameraWrapper(  236): camera_set_preview_window->41528FC0->41529018
D/CameraWrapper(  236): camera_set_preview_window->41528FC0->41529018
I/CameraClient(  236): Destroying camera 0
D/CameraWrapper(  236): camera_device_close
E/QualcommCamera(  236): Qint android::close_camera_device(hw_device_t_): device
 =0x41529018 E
E/mm-camera(  251): config_shutdown_pp Camera not in streaming mode. Returning.

E/mm-camera(  251): ispif_client_process: event type =7
E/mm-camera(  251): ispif_parse_handle: handle = 0x100, client_idx = 0
E/mm-camera(  251): ispif_process_release called
E/mm-camera(  251): ispif_client_destroy: handle = 0x100
E/mm-camera(  251): ispif_parse_handle: handle = 0x100, client_idx = 0
I/Sensors (  212): DSPS file:sns_smgr_sol.c(1230):SMGR: One val: 2
I/Sensors (  212): DSPS file:sns_smgr_sol.c(1230):SMGR: One val: 1
E/QCameraHWI_Preview(  236): virtual void android::QCameraStream_preview::releas
e() : BEGIN
E/QCameraHWI_Preview(  236): : virtual void android::QCameraStream_preview::rele
ase() : De init Channel
E/QCameraHWI_Preview(  236): virtual void android::QCameraStream_preview::releas
e(): END
I/mm-still-omx(  236): omxJpegClose:
E/QCameraHWI_Rdi(  236): virtual void android::QCameraStream_Rdi::release() : BE
GIN
E/QCameraHWI_Rdi(  236): : virtual void android::QCameraStream_Rdi::release() :
De init Channel
E/QCameraHWI_Rdi(  236): virtual void android::QCameraStream_Rdi::release(): END

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41512168 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x415120b0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41513af0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x415127a8 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41520670 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41512640 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41512500 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x415122f0 successful

W/AudioFlinger(  236): session id 28 not found for pid 236
I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41528860 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x415216f0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x415222a8 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41522128 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41528e60 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41528d38 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x41528bf8 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x415289e8 successful

W/AudioFlinger(  236): session id 29 not found for pid 236
V/CameraHolder( 1666): open camera 1
D/CameraWrapper(  236): camera_get_camera_info
D/CameraWrapper(  236): check_vendor_module
E/QualcommCamera(  236): Qint android::get_camera_info(int, camera_info*): E
I/AwesomePlayer(  236): setDataSource_l(URL suppressed)
D/QCUtilClass(  236): extended extractor not needed, return default
D/AwesomePlayer(  236): Tunnel Mime Type: audio/vorbis, object alive = 0, mTunne
lAliveAP = 0
D/AwesomePlayer(  236): Normal Audio Playback
D/AwesomePlayer(  236): Use tunnel player only for AUDIO_STREAM_MUSIC
I/AwesomePlayer(  236): setDataSource_l(URL suppressed)
D/QCUtilClass(  236): extended extractor not needed, return default
D/AwesomePlayer(  236): Tunnel Mime Type: audio/vorbis, object alive = 0, mTunne
lAliveAP = 0
D/AwesomePlayer(  236): Normal Audio Playback
D/AwesomePlayer(  236): Use tunnel player only for AUDIO_STREAM_MUSIC
I/CameraClient(  236): Opening camera 1
D/CameraWrapper(  236): camera_device open
D/CameraWrapper(  236): check_vendor_module
E/QualcommCamera(  236): Qint android::get_number_of_cameras(): E
E/mm-camera(  251): AWB CALI rg:0x40a7, bg:0000 rb:0000
I/Sensors (  212): DSPS file:sns_smgr_sol.c(1338):SMGR: One val: 2
I/Sensors (  212): DSPS file:sns_smgr_sol.c(1338):SMGR: One val: 3
E/mm-camera(  251): sensor_load_chromatix: libchromatix_imx132_preview.so: 30
E/mm-camera(  251): Failed to dlopen libchromatix_imx132_preview.so: Cannot load
 library: load_library(linker.cpp:771): library "libchromatix_imx132_preview.so"
 not found
E/mm-camera(  251): sensor_init:198:Error:Failed to load chromatix file
E/mm-camera(  251): mctl_init: sensor_interface_init failed: handle = 0x200, rc
= -22
E/mm-camera(  251): cam_mctl_thread: mctl_init() error
E/mm-camera(  251): wait_cam_mctl_thread_ready: mctl thread opened but failed du
ring init
E/mm-libcamera2(  236): mm_camera_open:  ctrl_fd = 40
E/mm-libcamera2(  236): Errno:2
E/mm-libcamera2(  236): mm_camera_open:  opened, break out while loop
E/mm-libcamera2(  236): mm_camera_open:  after while loop
E/mm-libcamera2(  236): mm_camera_open:  2
E/mm-libcamera2(  236): mm_camera_socket_create: socket_fd=-1 No such file or di
rectory
E/mm-libcamera2(  236): mm_camera_open:  ds_fd = -1
E/mm-libcamera2(  236): Errno:2
E/mm-libcamera2(  236): mm_camera_socket_create: socket_fd=-1 No such file or di
rectory
E/mm-libcamera2(  236): mm_camera_open:  ds_fd = -1
E/mm-libcamera2(  236): Errno:2
E/mm-libcamera2(  236): mm_camera_open:  opened, break out while loop
E/mm-libcamera2(  236): mm_camera_open:  after while loop for domain socket open

E/mm-libcamera2(  236): mm_camera_open: cannot open domain socket fd of 'video2'
 Errno = 2
I/Sensors (  212): DSPS file:sns_smgr_sol.c(1230):SMGR: One val: 2
I/Sensors (  212): DSPS file:sns_smgr_sol.c(1230):SMGR: One val: 1
E/QCameraHWI(  236): startCamera: cam_ops_open failed: id = 1
E/QCameraHWI(  236): isCameraReady mCameraState 0
E/QualcommCamera(  236): int android::camera_device_open(const hw_module_t_, cha
r const_, hw_device_t**):  end rc -1
E/CameraWrapper(  236): vendor camera open fail
E/CameraClient(  236): Could not open camera 1: -1
E/CameraClient(  236): initialize: Camera 1: unable to initialize device: Operat
ion not permitted (-1)
I/CameraClient(  236): Destroying camera 1
I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154d478 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154d3c0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154d2f0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154d1b0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154da78 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154d950 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154d810 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154d600 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154f868 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154f7b0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154f6e0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154f5a0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154fdf0 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154fcc8 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154fb88 successful

I/OMXNodeInstance(  236): OMX_FreeBuffer for buffer header 0x4154f9f0 successful

E/CameraHolder( 1666): fail to connect Camera
E/CameraHolder( 1666): java.lang.RuntimeException: Fail to connect to camera ser
vice
E/CameraHolder( 1666):  at android.hardware.Camera.native_setup(Native Method)
E/CameraHolder( 1666):  at android.hardware.Camera.<init>(Camera.java:340)
E/CameraHolder( 1666):  at android.hardware.Camera.open(Camera.java:302)
E/CameraHolder( 1666):  at com.android.camera.CameraManager.cameraOpen(CameraMan
ager.java:291)
E/CameraHolder( 1666):  at com.android.camera.CameraHolder.open(CameraHolder.jav
a:210)
E/CameraHolder( 1666):  at com.android.camera.Util.openCamera(Util.java:486)
E/CameraHolder( 1666):  at com.android.camera.PhotoModule.switchCamera(PhotoModu
le.java:2844)
E/CameraHolder( 1666):  at com.android.camera.PhotoModule.access$2300(PhotoModul
e.java:89)
E/CameraHolder( 1666):  at com.android.camera.PhotoModule$MainHandler.handleMess
age(PhotoModule.java:417)
E/CameraHolder( 1666):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraHolder( 1666):  at android.os.Looper.loop(Looper.java:137)
E/CameraHolder( 1666):  at android.app.ActivityThread.main(ActivityThread.java:5
227)
E/CameraHolder( 1666):  at java.lang.reflect.Method.invokeNative(Native Method)
E/CameraHolder( 1666):  at java.lang.reflect.Method.invoke(Method.java:511)
E/CameraHolder( 1666):  at com.android.internal.os.ZygoteInit$MethodAndArgsCalle
r.run(ZygoteInit.java:795)
E/CameraHolder( 1666):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.ja
va:562)
E/CameraHolder( 1666):  at dalvik.system.NativeStart.main(Native Method)

**Comment by ivan19871002** [comment]
Fixed
Look this 
https://github.com/mitwo-dev/proprietary_vendor_xiaomi/commit/f25234bfa452a62c2abed2039e05361798db560d
