### ISSUE TITLE
Open Source Kernel

### ISSUE THREAD

**Issue by grondinm** [mitwo-dev/android_device_xiaomi_aries#7]
Please give us kernel sources. It will be more in line with the android way and will allow the entire community to work on fixing issues(like screen tearing)

**Comment by ivan19871002** [comment]
please wait.

**Comment by grondinm** [comment]
any closer to this happening??

**Comment by M1cha** [comment]
xiaomi will never officially publish sources but I'm making much progress with developing/reverse engineering my own kernel: 
https://github.com/M1cha/android_kernel_xiaomi_aries
http://miuiandroid.com/community/threads/dev-opensource-kernel.19934/

**Comment by grondinm** [comment]
Have they actually said that? ivan19871002 just said to wait...I have been watching your progress keep it up.

**Comment by M1cha** [comment]
yes, a xiaomi employee said that to me.

**Comment by grondinm** [comment]
well that sucks. Any reasoning given? Not that any would be acceptable. Do they not realize or care that they are breaking the law by not releasing sources for kernel?

**Comment by M1cha** [comment]
They just don't because noone can do something about it.
I think the reason why they published android sources was just a desperate move to prevent people from moving to opensource devices.

The bad thing about this is that they sorta stole me the show. The good thing is that I have less work and the community is happy.

**Comment by grondinm** [comment]
Well i was happy to see some more openess from them but if not kernel sources are to follow i am not as happy...how can no one do anything. It's a license it applies world wide does it not...

**Comment by ivan19871002** [comment]
I am sorry about opensource.My application is not allowed.
But What if you need to modify or add any code, you can just tell me, I can do a good job

**Comment by shrthndin** [comment]
@ivan19871002 Could you please modify the camera driver to support true 1080/30fps recording and lockable preview frame rates(ie... 0-120 preview range)? Please check my ticket.

**Comment by anonyxin** [comment]
@ivan19871002 Could  help with the M1cha's opensource kernel. Now everything works without the cam.

**Comment by M1cha** [comment]
Well I think this issue can be closed soon ;)

**Comment by anonyxin** [comment]
@M1cha The issue can be closed as soon as the camera works on your kernel.

**Comment by Ryotsuke** [comment]
This "soon" lasts from beginning of this year )
Set a date.

**Comment by ivan19871002** [comment]
opensource  url  https://github.com/MiCode/mi2_kernel   or you can get it from mitwo-dev

**Comment by grondinm** [comment]
Is this direct from xiaomi or is this based on or contributed by m1cha?

**Comment by ivan19871002** [comment]
you can use it on miui v5. if you want use it on 4.2 or 4.3 ，you must merge some codes from caf

**Comment by ivan19871002** [comment]
I will release  kernel source for mi2/2s/2a ,  It is support android 4.3

**Comment by M1cha** [comment]
@grondinm Is it the stock 4.1 kernel source from xiaomi.

**Comment by ivan19871002** [comment]
https://github.com/mitwo-dev/mi2_kernel/tree/android-4.3    

for android-4.3
