### ISSUE TITLE
Can not pass Antutu's benchmark

### ISSUE THREAD

**Issue by ghost** [mitwo-dev/android_device_xiaomi_aries#8]
今天跑了一下安兔兔的分，发现非常不稳定。
尤其是OpenGL ES 2.0的测试，根本无法进行。现象是黑屏死机而且屏幕有一条亮线。
另外，2D的分数只有几百分，按道理要上千。3D的分数更不用说。
关于屏幕撕裂的问题，估计是与CPU渲染有关。因为我启用“停用HW渲染层（始终GPU渲染）”，问题貌似解决。但是这不是长远之计，毕竟要解决内核问题。
还有，请教您一个问题：把内核换成miui所用的内核可以吗？还需不需要修改内核头文件？如果要修改，从哪里得到内核头文件？
最后一个问题请教您：MI1／MI2所用的内核是基于CAF吗？
非常感谢您为MI2所做一切。

**Comment by ivan19871002** [comment]
不能通用，内核使用的是nexus4的 内核。所以问题很多。

发件人:  Darkgenlotus notifications@github.com
答复:  mitwo-dev/android_device_xiaomi_aries
<reply+i-16857110-9b3c59340d0c4e1b3816f3cba6773c318ab9cc55-836387@reply.gith
ub.com>
日期:  2013年7月17日星期三 下午6:15
至:  mitwo-dev/android_device_xiaomi_aries
android_device_xiaomi_aries@noreply.github.com
主题:  [android_device_xiaomi_aries] Can not pass Antutu's benchmark (#8)

今天跑了一下安兔兔的分，发现非常不稳定。
尤其是OpenGL ES 2.0的测试，根本无法进行。现象是黑屏死机而且屏幕有一条亮线。
另外，2D的分数只有几百分，按道理要上千。3D的分数更不用说。
关于屏幕撕裂的问题，估计是与CPU渲染有关。因为我启用“停用HW渲染层（始终GPU渲
染）”，问题貌似解决。但是这不是长远之计，毕竟要解决内核问题。
还有，请教您一个问题：把内核换成miui所用的内核可以吗？还需不需要修改内核头文件？
如果要修改，从哪里得到内核头文件？
最后一个问题请教您：MI1／MI2所用的内核是基于CAF吗？
非常感谢您为MI2所做一切。

—
Reply to this email directly or view it on GitHub
https://github.com/mitwo-dev/android_device_xiaomi_aries/issues/8 .
