### ISSUE TITLE
Screen wake up

### ISSUE THREAD

**Issue by kekkojoker90** [mitwo-dev/android_device_xiaomi_aries#9]
Screen wake up many times without touching the power button. Before i thinks is the problem of the rom but after speak with other persons seems this problem is widespread (in the kernel's version released today)

Best reguard kekkojoker90

**Comment by grondinm** [comment]
I am also seeing this on AOKP so it's not just CM. I think this might have been fixed with the latest commits. Can't test not at home but will rebuild my builds when i do and report.

**Comment by M1cha** [comment]
It's possible that I saw this on my opensource kernel, too but I thought I've just pressed the power button one time to often because it turned on 1s after turning the screen of.

**Comment by kekkojoker90** [comment]
Guys it's random, at the beginning when i have saw i have thought it is a feature like tap to wake or tap on the home buttone to wake. After many try to understand how is work i came to the conclusion it's a bug.

**Comment by grondinm** [comment]
thank you for looking into this so quickly. hope for a fix soon. It's gotta be something with this commit as it did not do it before

https://github.com/mitwo-dev/android_device_xiaomi_aries/commit/2619264556ed0718c51d1f16f0ace0008c4faded

I will also add that it does not do it at all when charger is plugged in if that helps...

**Comment by M1cha** [comment]
That means it's a problem of codeaurora  kernel. They have much problems because they are so generic. I've already imported much from nexus4 kernel like updated wlan drivers and gcc4.7 fixes but about this issue I currently don't have a idea.

**Comment by grondinm** [comment]
We will see how much it affects battery life. if it's minimal then it's not as big an issue as it could be. still needs investigation. i will leave that to those with access/are more familiar to kernel source

**Comment by ivan19871002** [comment]
I add support mhl. And thery have  a wake lock . it cant unlock. so  the screen wake.i will fix it in few days

**Comment by ivan19871002** [comment]
Fixed
This commit https://github.com/mitwo-dev/android_device_xiaomi_aries/commit/bf28ee75b64329aab1f6bfe815c783ec0ed65f87

**Comment by grondinm** [comment]
thank you.
